mySap/urls.py
from django.contrib import admin
from django.urls import path, include

from mySap.views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('', include("tasks.urls")),
]

tasks/urls.py
from django.urls import path

from tasks.views import all_task_views, task_view, task_modify, my_tasks_list, add_new_task

app_name = "tasks"
urlpatterns = [
    path('', all_task_views,name="home"),
    path('task/<int:id>/', task_view,name="task_view"),
    path('task/<int:id>/modify/', task_modify,name="task_modify"),
    path('task/my/', my_tasks_list,name="my_tasks_list"),
    path('task/add/', add_new_task,name="add_new_task"),
]

tasks/models.py
from django.contrib.auth.models import User
from django.db import models


class Task(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, auto_created=True)
    is_assigned = models.BooleanField(default=False)
    assigned_user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    task_name = models.CharField(max_length=200)
    task_description = models.TextField()
    deadline = models.DateTimeField()
    is_finished = models.BooleanField(default=False)
    finished_date = models.DateTimeField(null=True,blank=True)
    is_seen = models.BooleanField(default=False)

    def __str__(self):
        return self.task_name




class TaskDetails(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE,related_name="all_task_details")
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    modify_date = models.DateTimeField(auto_created=True,auto_now_add=True)
    modify_desc = models.TextField()

    def __str__(self):
        return self.task.task_name + " [ " + str(self.modify_date) + " ]"

tasks/forms.py
from django import forms

from tasks.models import Task


class TaskForm(forms.ModelForm):

    

    class Meta:
        model = Task
        fields = ['assigned_user', 'task_name', 'task_description', 'deadline']


        labels = {
            'assigned_user': 'Assigned user',
            'task_name': 'Task Name',
            'task_description': 'Task Description',
            'deadline': 'Deadline Date',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['task_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['task_description'].widget.attrs.update({'class': 'form-control'})
        self.fields['assigned_user'].widget.attrs.update({'class': 'form-control'})

        self.fields['deadline'].widget = forms.DateInput(attrs={'type':'datetime-local','class':'form-control'})

mySap/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import redirect, render


def login_view(request,*args,**kwargs):
    template = "base/login.html"
    context = {}

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request,username=username,password=password)
        if user is not None:
            login(request, user)
            return redirect("tasks:home")

    return render(request=request,template_name='base/login.html')


@login_required(login_url='login')
def logout_view(request):
    user = request.user
    print("---------")
    if user is not None:
        logout(request)
        return redirect("login")

tasks/views.py
import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.shortcuts import render, redirect

# Create your views here.
from tasks.forms import TaskForm
from tasks.models import Task, TaskDetails


@login_required(login_url="login")
def all_task_views(request):
    tasks = Task.objects.filter(is_finished=False).order_by('deadline')
    finished_task = None
    # ha rendelkezik boss jogsival, a befejezetteket is listázzuk
    if request.user.groups.filter(name="boss").exists():
        finished_task = Task.objects.filter(is_finished=True).order_by('deadline')

    context = {
        'data': tasks,
        'finished_data':finished_task
    }
    template = "tasks/all_task_views.html"
    return render(request, template, context)


@login_required(login_url="login")
def my_tasks_list(request):
    tasks = Task.objects.filter(assigned_user=request.user,is_finished=False).order_by('deadline')

    finished_task = Task.objects.filter(assigned_user=request.user,is_finished=True).order_by('deadline')
    context = {
        'data': tasks,
        'finished_data': finished_task
    }
    template = "tasks/all_task_views.html"
    return render(request, template, context)


@login_required(login_url="login")
def task_view(request, id):
    task = Task.objects.get(id=id)
    is_my_task = task.assigned_user == request.user

    if is_my_task:
        if task.is_seen is not True:
            task.is_seen = True
            task.save()

    context = {
        'data': task,
        'is_my_task': is_my_task #ez nem is feltétlen kell
    }
    template = "tasks/task_view.html"
    return render(request, template, context)


@login_required(login_url="login")
def task_modify(request, id):
    if request.method == 'POST':
        user = request.user
        task = Task.objects.get(id=id)

        if "description" in request.POST:
            desc = request.POST["description"]
        else:
            desc = "modifyed assigned user"

        if task.assigned_user != request.user:
            messages.success(request,"Taker your owned process")
            task.is_assigned = True
            task.assigned_user = request.user

        if 'finished' in request.POST:
            if request.POST['finished'] == 'on':
                messages.success(request, "Your finished the process")
                task.is_finished = True
                task.finished_date = datetime.datetime.now()

        task.save()

        obj = TaskDetails.objects.create(
            task=task,
            user_id=user,
            modify_desc=desc
        )
        obj.save()
        messages.success(request, "Create new process")
        return redirect("tasks:task_view", id=id)


@login_required(login_url="login")
def add_new_task(request):
    if request.user.groups.filter(name='boss').exists():
        form = TaskForm()

        if request.method == 'POST':
            form = TaskForm(request.POST)
            if form.is_valid():
                task = form.save(commit=False)
                if task.assigned_user is not None:
                    task.is_assigned = True

                task.save()

                messages.success(request,"Saved the new task")
                return redirect("/")





        template = 'tasks/add_task.html'
        context = {
            'form':form
        }
        return render(request=request,template_name=template,context=context)
    else:
        messages.warning(request,"Not allowed this function for you")
        return redirect("/")

tasks/templates/tasks/add_task.html
{% extends 'base/base.html' %}

{% block title %}TASK - Add new task{% endblock title %}


{% block content %}

<div class="card mx-auto" style="max-width:800px">
    <div class="card-body textPrimary"><h4 class="card-title">Add new task</h4></div>
    <div class="card-body textPrimary">
        <form action="" method="post">
            {%csrf_token%}
            {{form.as_p}}
            <input type="submit" class="btn btn-dark w-100" value="Save">
        </form>
    </div>
</div>


{% endblock content%}

tasks/templates/tasks/all_task_views.html
{% extends 'base/base.html' %}

{% block title %}Főoldal{% endblock title %}


{% block content %}
<div class="container ">
    <div class="infoBar">Available Tasks</div>
    <div class="row row-cols-1 row-cols-sm-1 row-cols-md-2 row-cols-lg-4">


    {% for task in data %}
        <div class="col p-1">
            <div class="card">
                  <div class="card-body {% if task.assigned_user == request.user %} assignedTask {% endif %}">
                    <h5 class="card-title textPrimary">{{task.task_name}}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Assigned: {{task.is_assigned}}</h6>
                      {% if task.is_assigned %}
                            <h6 class="card-subtitle mb-2 text-muted">Assigned to: {{task.assigned_user.username}}</h6>
                      {% endif %}
                    <p class="card-text textPrimaryDark">{{task.task_description|truncatechars:280}}</p>
                    <p class="card-text textPrimaryDark"><strong>Process numbers: {{task.all_task_details.all.count}}</strong></p>
                    <p class="card-text textPrimaryDark"><strong>Deadline: {{task.deadline | timeuntil}}</strong></p>
                    <a href="{% url 'tasks:task_view' task.pk %}" type="button" class="btn btn-outline-secondary">View<i class="bi bi-search p-2"></i></a>
                  </div>
            </div>
        </div>

    {% endfor %}

    </div>

    {% if is_boss_process %}
    <div class="infoBar">Finished Tasks</div>
    <div class="row row-cols-1 row-cols-sm-1 row-cols-md-2 row-cols-lg-4">
        {% for task in finished_data %}
            <div class="col p-1">
                <div class="card text-secondary">
                      <div class="card-body bg-dark text-secondary {% if task.assigned_user == request.user %} assignedTask {% endif %}">
                        <h5 class="card-title text-light">{{task.task_name}}</h5>
                        <h6 class="card-subtitle mb-2 ">Assigned: {{task.is_assigned}}</h6>
                          {% if task.is_assigned %}
                                <h6 class="card-subtitle mb-2 ">Assigned to: {{task.assigned_user.username}}</h6>
                          {% endif %}
                        <p class="card-text ">{{task.task_description}}</p>
                        <p class="card-text "><strong>Process numbers: {{task.all_task_details.all.count}}</strong></p>
                        <p class="card-text "><strong>Deadline: {{task.deadline | timeuntil}}</strong></p>
                        <p class="card-text text-light "><strong>Finished: {{task.finished_date }}</strong></p>
                        <a href="{% url 'tasks:task_view' task.pk %}" type="button" class="btn btn-outline-secondary">View<i class="bi bi-search p-2"></i></a>
                      </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% endif %}


</div>
{% endblock content%}

tasks/templates/tasks/task_view.html
{% extends 'base/base.html' %}

{% block title %}TASK - {{data.task_name}}{% endblock title %}


{% block content %}
<div class="container ">
    <div class="infoBar">Task - {{data.task_name}}</div>
    <div class="card">
          <div class="card-body">
            <h5 class="card-title textPrimary">{{data.task_name}}</h5>
            <h6 class="card-subtitle mb-2 text-muted">Assigned: {{data.is_assigned}}</h6>
            {% if data.is_assigned %}
                <h6 class="card-subtitle mb-2 text-muted">Assigned to: {{data.assigned_user.username}}</h6>
            {% endif %}
            <p class="card-text textPrimaryDark">{{data.task_description}}</p>
            {% if not is_my_task%}
            <form action="{% url 'tasks:task_modify' data.pk %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-warning">I will take over<i class="bi bi-arrow-bar-left p-2"></i></button>
            </form>
            {% endif %}
          </div>
    </div>




    <div class="infoBar">Task process</div>

    {% for t in data.all_task_details.all|dictsortreversed:"modify_date" %}
    <div class="card mt-1 bgPrimary">
          <div class="card-body">
            <h5 class="card-title textSecondary">{{t.user_id.username}}</h5>
            <h6 class="card-subtitle mb-2 text-muted">Modify:{{t.modify_date}}</h6>
            <p class="card-text text-muted">{{t.modify_desc}}</p>
          </div>
    </div>
    {% empty %}
    <h5>--- no process yet</h5>
    {% endfor %}


    {% if is_my_task and data.is_finished is not True %}
    <div class="card mt-3 textPrimary">
    <form action="{% url 'tasks:task_modify' data.pk %}" method="post">
        {% csrf_token %}
        <div class="card-body"><h3 class="card-title textPrimary">New process save</h3></div>
        <div class="card-body">
            <label for="description" class="form-label">Process description</label>
            <textarea class="form-control" id="description" name="description" rows="5" ></textarea>
            <button type="submit" class="btn btn-dark mt-3" value="Save">Save<i class="bi bi-arrow-up-right-square p-2"></i></button>
        </div>
        <div class="card-footer">
            <div class="form-check form-switch">
              <input class="form-check-input" name="finished" type="checkbox" role="switch" id="flexSwitchCheckChecked" >
              <label class="form-check-label" for="flexSwitchCheckChecked">This process is finished</label>
            </div>
        </div>
    </form>
    </div>
    {% endif %}


</div>

{% endblock content%}

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
  <link href="{% static 'main.css' %}" rel="stylesheet">
  <link rel="icon" type="image/x-icon" href="{% static 'ico/task.ico' %}">

  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">


  <title>MiniSap {% block title %}{% endblock title %}</title>
</head>
<body>
{% include 'includes/navbar.html' %}
<div class="container-fluid mainDiv">
  <div class="container">{% include 'includes/messages.html' %}</div>

  {%block content%}

  {% endblock content%}
</div>

{% include 'includes/footer.html' %}
</body>
</html>

templates/base/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
  <link href="{% static 'main.css' %}" rel="stylesheet">

  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>MiniSap Login</title>
</head>
<body>
  <div class="container  p-3" style="height:100vh">

    <div class="card bg-dark text-light mx-auto" style="max-width:800px" >
      <div class="card-body">
          <h3 class="card-title">Login</h3>

          <form method="post" action="">
              {% csrf_token %}
              <label for="username" class="form-label">Username</label>
              <input class="form-control bg-dark text-light" required name="username" id="username" placeholder="Username">
              <label for="password" class="form-label">Password</label>
              <input class="form-control bg-dark text-light" type="password" required name="password" id="password" placeholder="Password">
              <input type="submit" class="btn btn-dark mt-2 w-100" value="Bejelentkezés">
          </form>


      </div>
    </div>
</div>

</body>
</html>

templates/includes/footer.html
<div class="container-fluid footer">
    <div class="text-center p-0 textSecondary">THIS IS MINI SAP SOLUTION MANAGER</div>
    <div class="text-center p-0 m-0 text-light">present by hybase | reference and template mini project </div>
    <div class="container text-center">
  <div class="row mt-3 text-secondary">
        <div class="col">
            <a class="btn btn-dark" href="mailto:hybase@outlook.hu">hybase@outlook.hu</a>
        </div>
        <div class="col">
          <a class="btn btn-dark" href="https://www.linkedin.com/in/nagy-istvan88/">LinkedIn</a>
        </div>
        <div class="col">
          <a class="btn btn-dark" href="https://github.com/hybase-hu">GitHub</a>
        </div>
      </div>
    </div>
</div>

templates/includes/messages.html
{% if messages %}

    {% for message in messages %}
    <div class="alert alert-{{message.tags}} mt-3">
        {{ message }}
    </div>

    {% endfor %}

{% endif %}

templates/includes/navbar.html
<nav class="navbar navbar-dark bg-dark fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand position-relative" href="/">
      MiniSAP Solution Manager
        {% if not_seen_task|length > 0 %}
          <span class="position-absolute top-20  start-100 translate-middle badge rounded-pill bg-danger">
              {{not_seen_task|length}}
          </span>
       {% endif %}
    </a>

    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel"><i class="bi bi-person"> {{request.user.username}}</i></h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <a class="nav-link {% if '/' == request.path %}active{% endif %}" aria-current="page" href="/">Home</a>
          </li>

          {% if is_boss_process %}
          <li class="nav-item">
            <a class="nav-link {% if '/task/add/' == request.path %}active{% endif %}" href="{% url 'tasks:add_new_task' %}">Add new Task</a>
          </li>
          {% endif %}


          <li class="nav-item">
            <a class="nav-link {% if '/task/my/' == request.path %}active{% endif %}" href="{% url 'tasks:my_tasks_list' %}">My Tasks</a>
          </li>

          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link " href="{% url 'logout' %}">Logout</a>
          </li>
          {% endif %}


        </ul>
        <!--
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-success" type="submit">Search</button>
        </form>
        -->
      </div>
    </div>
  </div>
</nav>